-- RichGuyLos Radio Station: server-delivered CSP online script.
--
-- Copyright (c) 2026 RichGuyLos. All rights reserved.
-- Created and owned by RichGuyLos. Not licensed for redistribution, rehosting
-- or use on any server other than those authorised below. Contact the author
-- for permission.
-- Uses CSP/Windows Media Foundation directly: no Python, VLC or local bridge.
--
-- PRIVATE BUILD. The station list in this file is encrypted, and the key is the
-- identity of the server serving it - address, port and name. Nothing secret
-- goes in the server config, so nobody with panel or admin access sees a key.
-- Run this file on any other server and it decrypts to nothing.
--
-- Generated by pack_radio.py - edit stations.json and repack, not this file.

local SALT = '4ea355ab5fefa21c2a2bfb080a14b006'
local TAG  = '0decd3291b4c76d0aabad039fd541922bb9acba14d314cd7de432bd3ecc49035'
local ITER = 2000
local BLOB = '47bd44534b8d11bcc8a376fc02c700769fb0c09971b00e2b6ffd05eeab453d058a1db4875ad3751ad91c11ddd1260dfec41a2f71f78f92082d539294c80f815fd2c8d5547147e355e0f6ecbef9db20811f2607648f87baff371eb2e4441a332d56c85e199e112e7b994db4940a0cd1535760bc29063e6fc62590af6accfb185e94f14f5f2e1ddbabddc69588eb2a8a025aba88119156ba0c9c2b26bd0418d17dfbf6dd0482e857890c691e14a25cd57f5a9f3096ce2895b3e9d790c54d08465fd734f843e53d954247117dab2a20725bf21301eecc8abd6dc0d4e1ab211b5d7add4f37962531e028edbc863253c044273c8699730182c0f51ac3b7a4bb2f09cb3646f1849a7c4b39817e234b65237dd58aa9942b71d55c1890fbfd2991290cb4345b2a028844319fcd81d0dffcaf5d539d5dd90aaa7f4eb2c838c7e718e445be9ca4309ecc5095f46c69e1ca91220cbfb9b3c7e2354715c26b5839c4385b9a36096a4f1eef88d79e2b139f0aa3ddbaaa9d6a410cf98a69bf6dd794eb4e44bb646f0d4c4dc7ecd119302876e10ae4767bc606bf6313486d86085240237f633dafe3ce057df16caa7344b794b618613836d1f9bb9cd67e253ff7589568a8577b200488352b8d53289996cb940e01b0edb9461029c55cb6be982ed68d17272646d6621758385a7e9c201f4492173cd44c3b6b2da9110d45aa9c5aef8e13a57c7d19b1cdf078ceee029e8a2398dd7e888a6855df2d03757861121a68ea19f8c80cc1be6c5c6d98aacf9998f34ee97c74b02ed6495c94e74331ad137bc5b6909b58256e6076e73fd42f1033783d86f4db199e3fe300ea04f97e68d5007df22d75dcbfb70e463ac0bf181da836014a3326ede9298ba8a8f6dd29c6e1327da2a4e9fad6ec115ba2cc4a310791f711f90996c8721955'
-- One wrapped copy of the payload key per authorised server.
local LOCKS = { '7e57b2b3218a1b82963b67fa2427fc2ab4dde09a2c74c026b4246076498ec7b8' }
-- Set by `pack_radio.py --no-lock`: the payload key in the clear, which makes
-- this build run on any server. Empty in a locked build.
local OPEN = ''

-- ------------------------------------------------------------------
--  Payload
-- ------------------------------------------------------------------

--- ac.checksumSHA256 may hand back 32 raw bytes or a 64-char hex string
--- depending on build, so normalise to lowercase hex either way.
local function shaHex(value)
  local digest = ac.checksumSHA256(value)
  if not digest then return nil end
  if #digest == 64 then return digest:lower() end
  return (digest:gsub('.', function (char)
    return string.format('%02x', string.byte(char))
  end)):lower()
end

local function deriveKey(secret)
  local key = shaHex(SALT .. '|' .. secret)
  if not key then return nil end
  for _ = 1, ITER do
    key = shaHex(key .. SALT)
  end
  return key
end

--- Every shape the running server's identity might take. Whichever one this
--- build was locked to will match; the rest simply fail to unwrap.
local function serverIdents()
  local ip   = ac.getServerIP and ac.getServerIP() or ''
  local name = ac.getServerName and ac.getServerName() or ''
  local port = ac.getServerPortTCP and ac.getServerPortTCP() or 0
  local list = {}
  if ip ~= '' then
    list[#list + 1] = ip
    if port and port > 0 then list[#list + 1] = ip .. ':' .. port end
  end
  if name ~= '' then
    list[#list + 1] = name
    if ip ~= '' then list[#list + 1] = ip .. '|' .. name end
  end
  return list
end

--- Unwraps the payload key using the server identity, rather than any secret
--- stored in the server's config.
local function unwrapKey()
  -- Unlocked build: the key ships with the file, no server check at all.
  if OPEN ~= '' and shaHex(OPEN .. '#' .. BLOB) == TAG then return OPEN end

  for _, ident in ipairs(serverIdents()) do
    local derived = deriveKey(ident)
    if derived then
      for _, lock in ipairs(LOCKS) do
        local candidate = {}
        for i = 1, #lock / 2 do
          local wrapped = tonumber(lock:sub(i * 2 - 1, i * 2), 16)
          local mask = tonumber(derived:sub(i * 2 - 1, i * 2), 16)
          candidate[i] = string.format('%02x', (wrapped - mask) % 256)
        end
        candidate = table.concat(candidate)
        if shaHex(candidate .. '#' .. BLOB) == TAG then return candidate end
      end
    end
  end
  return nil
end

local function decrypt()
  local key = unwrapKey()
  if not key then return nil end

  local out, blockIndex, keystream = {}, -1, nil
  for i = 1, #BLOB / 2 do
    local block = math.floor((i - 1) / 32)
    if block ~= blockIndex then
      blockIndex = block
      keystream = shaHex(key .. ':' .. block)
    end
    local offset = ((i - 1) % 32) * 2
    local keyByte = tonumber(keystream:sub(offset + 1, offset + 2), 16)
    local cipherByte = tonumber(BLOB:sub(i * 2 - 1, i * 2), 16)
    out[i] = string.char((cipherByte - keyByte) % 256)
  end
  return table.concat(out)
end

local function parseStations(plain)
  local list = {}
  for line in plain:gmatch('[^\n]+') do
    local id, frequency, name, urls = line:match('^([^|]*)|([^|]*)|([^|]*)|(.*)$')
    if id then
      local entry = { id = id, frequency = frequency, name = name, urls = {} }
      for url in urls:gmatch('[^\t]+') do
        entry.urls[#entry.urls + 1] = url
      end
      if #entry.urls > 0 then list[#list + 1] = entry end
    end
  end
  return list
end

local stations = {}
local licensed = false

do
  local plain = decrypt()
  if plain then
    stations = parseStations(plain)
    licensed = #stations > 0
  end
end

-- ------------------------------------------------------------------
--  Radio
-- ------------------------------------------------------------------

-- Seconds a stream gets to produce audio before we fall through to its backup.
local CONNECT_TIMEOUT = 9
-- Full passes through a station's URL list before giving up on it, so a dead
-- station can't sit there reconnecting forever in the background.
local MAX_PASSES = 3

local selected = 1
local urlIndex = 1
local passes = 0
local volume = 0.55
local muted = false
local powered = licensed
local player = nil
local status = licensed and 'STARTING' or 'LOCKED'
local statusDetail = licensed and 'Loading CSP native audio'
  or 'This server is not authorised to run this radio'
local statusTimer = 0
local sinceTune = 0
local toastTimer = 1.5
local toastShown = false

local function currentStation()
  return stations[selected]
end

local function applyVolume()
  if player then
    player:setVolume(volume)
    player:setMuted(muted or not powered)
  end
end

local function tune(index, urlIdx)
  if not licensed then return end
  selected = ((index - 1) % #stations) + 1
  local station = currentStation()
  urlIndex = urlIdx or 1

  if not ui.MediaPlayer.supported() then
    status = 'UNAVAILABLE'
    statusDetail = 'CSP native media playback is not supported on this PC'
    powered = false
    return
  end

  if not player then
    player = ui.MediaPlayer(nil, { rawOutput = false, use3D = false })
  end

  powered = true
  muted = false
  status = 'TUNING'
  statusDetail = 'Opening ' .. station.name
  player:setSource(station.urls[urlIndex])
  player:setAutoPlay(true)
  applyVolume()
  player:play()
  statusTimer = 0
  sinceTune = 0
end

local function stopRadio()
  powered = false
  status = 'STOPPED'
  statusDetail = 'Radio off'
  if player then
    player:pause()
    player:setMuted(true)
  end
end

local function togglePower()
  if powered then
    stopRadio()
  else
    passes = 0
    tune(selected, 1)
  end
end

local function radioUI()
  ui.textColored('RICHGUYLOS RADIO STATION', rgbm(0.08, 0.88, 1.00, 1))
  ui.textColored('SERVER RADIO // NO BRIDGE', rgbm(1.00, 0.12, 0.68, 1))
  ui.separator()

  if not licensed then
    ui.textColored('LOCKED', rgbm(1.00, 0.29, 0.29, 1))
    ui.textWrapped('This radio was created by RichGuyLos and is locked to his '
      .. 'servers. It will not run anywhere else.')
    ui.separator()
    -- Shown so an authorised server that fails to match can be identified and
    -- added to the build. It leaks nothing: this is the public address anyone
    -- already types in to connect.
    ui.textColored('This server reports:', rgbm(0.46, 0.58, 0.72, 1))
    for _, ident in ipairs(serverIdents()) do
      ui.text('  ' .. ident)
    end
    return false
  end

  local station = currentStation()
  ui.text(status .. '  //  ' .. station.frequency)
  ui.textWrapped(statusDetail)
  ui.separator()

  for i, item in ipairs(stations) do
    if ui.selectable(item.frequency .. '  //  ' .. item.name, selected == i) then
      passes = 0
      tune(i, 1)
    end
  end

  ui.separator()
  ui.text('AUDIO OUTPUT // CSP NATIVE')
  local nextVolume = ui.slider('##rglRadioVolume', volume * 100, 0, 100, '%.0f%%') / 100
  if math.abs(nextVolume - volume) > 0.001 then
    volume = nextVolume
    applyVolume()
  end

  if ui.button(powered and 'POWER OFF' or 'POWER ON', vec2(105, 32)) then
    togglePower()
  end
  ui.sameLine()
  if ui.button(muted and 'UNMUTE' or 'MUTE', vec2(90, 32)) then
    muted = not muted
    applyVolume()
  end
  ui.sameLine()
  if ui.button('RECONNECT', vec2(105, 32)) then
    passes = 0
    tune(selected, 1)
  end

  ui.textColored('Voice chat: CSP Mumble // positional PTT', rgbm(0.28, 1.00, 0.58, 1))
  return false
end

ui.registerOnlineExtra(
  ui.Icons.Radio,
  { title = 'RichGuyLos Radio Station', tooltip = 'Native server radio controls' },
  nil,
  radioUI,
  nil,
  ui.OnlineExtraFlags.Tool,
  ui.WindowFlags.None,
  vec2(390, 430)
)

if licensed then
  ui.MediaPlayer.supportedAsync(function (supported)
    if supported then
      tune(selected, 1)
    else
      status = 'UNAVAILABLE'
      statusDetail = 'CSP native media playback is not supported on this PC'
      powered = false
    end
  end)
end

function script.update(dt)
  if not licensed then return end

  statusTimer = statusTimer + dt
  sinceTune = sinceTune + dt
  toastTimer = toastTimer - dt

  if not toastShown and toastTimer <= 0 then
    toastShown = true
    ui.toast(ui.Icons.Radio, 'RichGuyLos Radio Station is playing. Open Chat > lightbulb for stations and volume.')
  end

  if not player or not powered then return end

  if player:playing() then
    -- Audio is flowing, so a stream that dies hours from now still gets a full
    -- set of retries rather than inheriting an old failure count.
    passes = 0
    if statusTimer >= 0.5 then
      statusTimer = 0
      status = muted and 'MUTED' or 'PLAYING'
      statusDetail = currentStation().name ..
        (urlIndex > 1 and ' // backup stream' or ' // live stream')
    end
    return
  end

  if sinceTune < CONNECT_TIMEOUT then
    if statusTimer >= 0.5 then
      statusTimer = 0
      status = player:hasAudio() and 'BUFFERING' or 'CONNECTING'
      statusDetail = 'Opening ' .. currentStation().name
    end
    return
  end

  -- Silent past the timeout: move to this station's next URL, and once the list
  -- is exhausted start it over until MAX_PASSES.
  local station = currentStation()
  if station.urls[urlIndex + 1] then
    tune(selected, urlIndex + 1)
  else
    passes = passes + 1
    if passes >= MAX_PASSES then
      status = 'UNAVAILABLE'
      statusDetail = station.name .. ' is not responding // pick another station'
      powered = false
      player:pause()
    else
      tune(selected, 1)
    end
  end
end
