-- RichGuyLos Radio Station: server-delivered CSP online script.
-- Uses CSP/Windows Media Foundation directly: no Python, VLC or local bridge.
--
-- PRIVATE BUILD. The station list in this file is encrypted, and the key is the
-- identity of the server serving it - address, port and name. Nothing secret
-- goes in the server config, so nobody with panel or admin access sees a key.
-- Run this file on any other server and it decrypts to nothing.
--
-- Generated by pack_radio.py - edit stations.json and repack, not this file.

local SALT = 'd0de9ad6cd6d151c955131a557e4c25e'
local TAG  = '355acc14a7814ea3dd016f72caedd43622a4bdc16e2d8648cc3fb06d3ed73cf1'
local ITER = 2000
local BLOB = '894113260e2b2167595819889b305aefe826987ef278617db6753b804fba6f0b257c1cbccfd5cd0741441e3645672ce1de4b2de95b50a4192fca0d6572d8930d329484061a6be01b08d5d2469e1896c12bdf2b3af160f4f7958fa5a1372ea64c547f038a3a00dbdaa462e701997dd4e79e976f095425ca05cb5e95e839fd2773d3f940d22465888fb9bf0c00b07a9dcf03dd5d5f6e64082208a60348d98ca949418577a2e4468d57959899850b8d0cef6487cf6ce9c7080377f469f3ec0d4bab76f0869b4657dffbd305a5553e45e61047c1c4d344d5a1656ab01d84609abbbbbb23b9f0e2614b5a2de5cdf7f6259b0e7caa41fab80ad9e98937e8cba04492ed7ecb0b60db796e4194d8d25dff4c3c5fe490d144d5ff9486110f070d1ea3b593bd0b0e8f2e6e7cbfa99d935058ae80dfe646ee61d30eccbd65a608961c6215fe2a89d386d7160e03e1cf79aeb3598eb26c89ec2b1cfd72bab243380c4cf55c0444d7ff47dd0cdd54d740f57c5f164379ea78c2e4fd60ccdefc614e0c8c180142d5ed5d7df844c078decbbc7e4cdc4adf6fb9eb07a5d7cebf27be74a60b351615aeb24bcc42aaa63e40d3239a927185cbee123a7ea9e84ae07bef1e8a58b8ec7d6e1fddf9bf0f298fc6f3bc5a5ce166196670c6965fcf40159482e122d43601cde1085e83421a9bb6b5429fbffc2f2defb7c750f0765628e94217c69a3e0e864c1b33e4f8f8af2eab2bb829c34892e436c1325ea3292451e7f69041b426d4242528f011f1a2c51259184e508514743932d7cd866da3a9ff14e5061987fa7f213a52e9f9346ab1972fc0d37b74d1fb2c9f7fe32d77da0a9eb3a8e06039ee89d475eb61cda2bb732f16836fce75f7170961244063b26ba1ecb98e4fa00ac3ff599ac2c2d6b464a1831c23fe270a4a942073bbb0'
-- One wrapped copy of the payload key per authorised server.
local LOCKS = { '12946269d807932c20ad4800a6211322f921ab66c345bc5fc5cf36573b73e21a' }

-- ------------------------------------------------------------------
--  Payload
-- ------------------------------------------------------------------

--- ac.checksumSHA256 may hand back 32 raw bytes or a 64-char hex string
--- depending on build, so normalise to lowercase hex either way.
local function shaHex(value)
  local digest = ac.checksumSHA256(value)
  if not digest then return nil end
  if #digest == 64 then return digest:lower() end
  return (digest:gsub('.', function (char)
    return string.format('%02x', string.byte(char))
  end)):lower()
end

local function deriveKey(secret)
  local key = shaHex(SALT .. '|' .. secret)
  if not key then return nil end
  for _ = 1, ITER do
    key = shaHex(key .. SALT)
  end
  return key
end

--- Every shape the running server's identity might take. Whichever one this
--- build was locked to will match; the rest simply fail to unwrap.
local function serverIdents()
  local ip   = ac.getServerIP and ac.getServerIP() or ''
  local name = ac.getServerName and ac.getServerName() or ''
  local port = ac.getServerPortTCP and ac.getServerPortTCP() or 0
  local list = {}
  if ip ~= '' then
    list[#list + 1] = ip
    if port and port > 0 then list[#list + 1] = ip .. ':' .. port end
  end
  if name ~= '' then
    list[#list + 1] = name
    if ip ~= '' then list[#list + 1] = ip .. '|' .. name end
  end
  return list
end

--- Unwraps the payload key using the server identity, rather than any secret
--- stored in the server's config.
local function unwrapKey()
  for _, ident in ipairs(serverIdents()) do
    local derived = deriveKey(ident)
    if derived then
      for _, lock in ipairs(LOCKS) do
        local candidate = {}
        for i = 1, #lock / 2 do
          local wrapped = tonumber(lock:sub(i * 2 - 1, i * 2), 16)
          local mask = tonumber(derived:sub(i * 2 - 1, i * 2), 16)
          candidate[i] = string.format('%02x', (wrapped - mask) % 256)
        end
        candidate = table.concat(candidate)
        if shaHex(candidate .. '#' .. BLOB) == TAG then return candidate end
      end
    end
  end
  return nil
end

local function decrypt()
  local key = unwrapKey()
  if not key then return nil end

  local out, blockIndex, keystream = {}, -1, nil
  for i = 1, #BLOB / 2 do
    local block = math.floor((i - 1) / 32)
    if block ~= blockIndex then
      blockIndex = block
      keystream = shaHex(key .. ':' .. block)
    end
    local offset = ((i - 1) % 32) * 2
    local keyByte = tonumber(keystream:sub(offset + 1, offset + 2), 16)
    local cipherByte = tonumber(BLOB:sub(i * 2 - 1, i * 2), 16)
    out[i] = string.char((cipherByte - keyByte) % 256)
  end
  return table.concat(out)
end

local function parseStations(plain)
  local list = {}
  for line in plain:gmatch('[^\n]+') do
    local id, frequency, name, urls = line:match('^([^|]*)|([^|]*)|([^|]*)|(.*)$')
    if id then
      local entry = { id = id, frequency = frequency, name = name, urls = {} }
      for url in urls:gmatch('[^\t]+') do
        entry.urls[#entry.urls + 1] = url
      end
      if #entry.urls > 0 then list[#list + 1] = entry end
    end
  end
  return list
end

local stations = {}
local licensed = false

do
  local plain = decrypt()
  if plain then
    stations = parseStations(plain)
    licensed = #stations > 0
  end
end

-- ------------------------------------------------------------------
--  Radio
-- ------------------------------------------------------------------

-- Seconds a stream gets to produce audio before we fall through to its backup.
local CONNECT_TIMEOUT = 9
-- Full passes through a station's URL list before giving up on it, so a dead
-- station can't sit there reconnecting forever in the background.
local MAX_PASSES = 3

local selected = 1
local urlIndex = 1
local passes = 0
local volume = 0.55
local muted = false
local powered = licensed
local player = nil
local status = licensed and 'STARTING' or 'LOCKED'
local statusDetail = licensed and 'Loading CSP native audio'
  or 'This server is not authorised to run this radio'
local statusTimer = 0
local sinceTune = 0
local toastTimer = 1.5
local toastShown = false

local function currentStation()
  return stations[selected]
end

local function applyVolume()
  if player then
    player:setVolume(volume)
    player:setMuted(muted or not powered)
  end
end

local function tune(index, urlIdx)
  if not licensed then return end
  selected = ((index - 1) % #stations) + 1
  local station = currentStation()
  urlIndex = urlIdx or 1

  if not ui.MediaPlayer.supported() then
    status = 'UNAVAILABLE'
    statusDetail = 'CSP native media playback is not supported on this PC'
    powered = false
    return
  end

  if not player then
    player = ui.MediaPlayer(nil, { rawOutput = false, use3D = false })
  end

  powered = true
  muted = false
  status = 'TUNING'
  statusDetail = 'Opening ' .. station.name
  player:setSource(station.urls[urlIndex])
  player:setAutoPlay(true)
  applyVolume()
  player:play()
  statusTimer = 0
  sinceTune = 0
end

local function stopRadio()
  powered = false
  status = 'STOPPED'
  statusDetail = 'Radio off'
  if player then
    player:pause()
    player:setMuted(true)
  end
end

local function togglePower()
  if powered then
    stopRadio()
  else
    passes = 0
    tune(selected, 1)
  end
end

local function radioUI()
  ui.textColored('RICHGUYLOS RADIO STATION', rgbm(0.08, 0.88, 1.00, 1))
  ui.textColored('SERVER RADIO // NO BRIDGE', rgbm(1.00, 0.12, 0.68, 1))
  ui.separator()

  if not licensed then
    ui.textColored('LOCKED', rgbm(1.00, 0.29, 0.29, 1))
    ui.textWrapped('This build is licensed to RichGuyLos and is locked to his '
      .. 'servers. It will not run anywhere else.')
    ui.separator()
    -- Shown so an authorised server that fails to match can be identified and
    -- added to the build. It leaks nothing: this is the public address anyone
    -- already types in to connect.
    ui.textColored('This server reports:', rgbm(0.46, 0.58, 0.72, 1))
    for _, ident in ipairs(serverIdents()) do
      ui.text('  ' .. ident)
    end
    return false
  end

  local station = currentStation()
  ui.text(status .. '  //  ' .. station.frequency)
  ui.textWrapped(statusDetail)
  ui.separator()

  for i, item in ipairs(stations) do
    if ui.selectable(item.frequency .. '  //  ' .. item.name, selected == i) then
      passes = 0
      tune(i, 1)
    end
  end

  ui.separator()
  ui.text('AUDIO OUTPUT // CSP NATIVE')
  local nextVolume = ui.slider('##rglRadioVolume', volume * 100, 0, 100, '%.0f%%') / 100
  if math.abs(nextVolume - volume) > 0.001 then
    volume = nextVolume
    applyVolume()
  end

  if ui.button(powered and 'POWER OFF' or 'POWER ON', vec2(105, 32)) then
    togglePower()
  end
  ui.sameLine()
  if ui.button(muted and 'UNMUTE' or 'MUTE', vec2(90, 32)) then
    muted = not muted
    applyVolume()
  end
  ui.sameLine()
  if ui.button('RECONNECT', vec2(105, 32)) then
    passes = 0
    tune(selected, 1)
  end

  ui.textColored('Voice chat: CSP Mumble // positional PTT', rgbm(0.28, 1.00, 0.58, 1))
  return false
end

ui.registerOnlineExtra(
  ui.Icons.Radio,
  { title = 'RichGuyLos Radio Station', tooltip = 'Native server radio controls' },
  nil,
  radioUI,
  nil,
  ui.OnlineExtraFlags.Tool,
  ui.WindowFlags.None,
  vec2(390, 430)
)

if licensed then
  ui.MediaPlayer.supportedAsync(function (supported)
    if supported then
      tune(selected, 1)
    else
      status = 'UNAVAILABLE'
      statusDetail = 'CSP native media playback is not supported on this PC'
      powered = false
    end
  end)
end

function script.update(dt)
  if not licensed then return end

  statusTimer = statusTimer + dt
  sinceTune = sinceTune + dt
  toastTimer = toastTimer - dt

  if not toastShown and toastTimer <= 0 then
    toastShown = true
    ui.toast(ui.Icons.Radio, 'RichGuyLos Radio Station is playing. Open Chat > lightbulb for stations and volume.')
  end

  if not player or not powered then return end

  if player:playing() then
    -- Audio is flowing, so a stream that dies hours from now still gets a full
    -- set of retries rather than inheriting an old failure count.
    passes = 0
    if statusTimer >= 0.5 then
      statusTimer = 0
      status = muted and 'MUTED' or 'PLAYING'
      statusDetail = currentStation().name ..
        (urlIndex > 1 and ' // backup stream' or ' // live stream')
    end
    return
  end

  if sinceTune < CONNECT_TIMEOUT then
    if statusTimer >= 0.5 then
      statusTimer = 0
      status = player:hasAudio() and 'BUFFERING' or 'CONNECTING'
      statusDetail = 'Opening ' .. currentStation().name
    end
    return
  end

  -- Silent past the timeout: move to this station's next URL, and once the list
  -- is exhausted start it over until MAX_PASSES.
  local station = currentStation()
  if station.urls[urlIndex + 1] then
    tune(selected, urlIndex + 1)
  else
    passes = passes + 1
    if passes >= MAX_PASSES then
      status = 'UNAVAILABLE'
      statusDetail = station.name .. ' is not responding // pick another station'
      powered = false
      player:pause()
    else
      tune(selected, 1)
    end
  end
end
