-- RichGuyLos Radio Station: server-delivered CSP online script.
-- Created and owned by RichGuyLos.
-- Uses CSP/Windows Media Foundation directly: no Python, VLC or local bridge.
--
-- PRIVATE BUILD. The station list in this file is encrypted, and the key is the
-- identity of the server serving it - address, port and name. Nothing secret
-- goes in the server config, so nobody with panel or admin access sees a key.
-- Run this file on any other server and it decrypts to nothing.
--
-- Generated by pack_radio.py - edit stations.json and repack, not this file.

local SALT = '45cf66f79b120c384f553e3ae3ed414a'
local TAG  = 'be1be199a531831b5604e8f33d67d17ef1142c81ab4eefbd2eca08316d3704d6'
local ITER = 2000
local BLOB = '8045da072d29cc39898e0d476abacd37b9d1866bc27b096e6794e179aa4925dbba14e9b55ef0928308cfb7c1dbd7033281e766bd18d7e29f28087b5af646e041b6ddc84fd56f1a97d926a2732924266e15e4adc906fe1cc336a9106bf90a57e4a728dbbec4a6796fc2433d04899da88785d58049f374682de25263726a2328a35fc5884f17a9eb8e2fc02060a1bfed1e92d35cbc178e80a976cd27e637e40500eb290e81699e25c75a0ac2569edbf4f5c860954fab8d5749fd62ced3505158a5b941a4b7fc76856cc343b2c9efc93dd16e299b80021a3da24b78ad37eeeb93b5e1a61fc1d8d1980b2f85bcc1f19a492669379ff81e8899afecc4aed926426b9e5e5ccef4df41d7805549e15b4e5f9978f06793b5db9fb2b0a00f4267da3404cb0e687df236cfb62f69f05108fa3b47827c5333a483d1c0f9f801b93fa06c8d9b264acb89ddf082dbef246ab9d36b832574c9ea729770ab9076f0f81ed8c0b60cc4489b02b7bd84ca89ee35767644edbfb1c4244f3384b117a504aef7f68bdba8d588813dc5520cfe1e30fe989a909a8a7fdc74787b5aa49aeba0e88798662ce669b263363b5c33efc971336f11ac91aba2ffaf5675e63dab201d37f4d844b70f15447d9e8d09d57a3062d9f01365fdc2cafbb483dd6b240362dd60a292b99aaede96afa604455a9e796683b4616d3dc8b5328c47189428f8a19b0677f4d3303140f504b28a727325be4605590a2fa967939362695f545a07344a9a5713791bc0152384c802b6ea9de63054bcc5d431d7d7d760889b9b56ffaeaf36860e4b117d3dca613f5b25efcd5132757b39a6e42904e05b410bff64ada5a8688f6d413ff43ff2f0bf98e67f86642bf53ab379228b9813a1b7efe128c2015d4e30c6c21852a1eb6f15816ae94cc0eaa9bac56364d876df'
-- One wrapped copy of the payload key per authorised server.
local LOCKS = { 'a0df5c62df844ef8cf7c7465a3c51fbdbef37631da3c828dbcd5f6a5ee90139c' }
-- Set by `pack_radio.py --no-lock`: the payload key in the clear, which makes
-- this build run on any server. Empty in a locked build.
local OPEN = ''

-- ------------------------------------------------------------------
--  Payload
-- ------------------------------------------------------------------

--- ac.checksumSHA256 may hand back 32 raw bytes or a 64-char hex string
--- depending on build, so normalise to lowercase hex either way.
local function shaHex(value)
  local digest = ac.checksumSHA256(value)
  if not digest then return nil end
  if #digest == 64 then return digest:lower() end
  return (digest:gsub('.', function (char)
    return string.format('%02x', string.byte(char))
  end)):lower()
end

local function deriveKey(secret)
  local key = shaHex(SALT .. '|' .. secret)
  if not key then return nil end
  for _ = 1, ITER do
    key = shaHex(key .. SALT)
  end
  return key
end

--- Every shape the running server's identity might take. Whichever one this
--- build was locked to will match; the rest simply fail to unwrap.
local function serverIdents()
  local ip   = ac.getServerIP and ac.getServerIP() or ''
  local name = ac.getServerName and ac.getServerName() or ''
  local port = ac.getServerPortTCP and ac.getServerPortTCP() or 0
  local list = {}
  if ip ~= '' then
    list[#list + 1] = ip
    if port and port > 0 then list[#list + 1] = ip .. ':' .. port end
  end
  if name ~= '' then
    list[#list + 1] = name
    if ip ~= '' then list[#list + 1] = ip .. '|' .. name end
  end
  return list
end

--- Unwraps the payload key using the server identity, rather than any secret
--- stored in the server's config.
local function unwrapKey()
  -- Unlocked build: the key ships with the file, no server check at all.
  if OPEN ~= '' and shaHex(OPEN .. '#' .. BLOB) == TAG then return OPEN end

  for _, ident in ipairs(serverIdents()) do
    local derived = deriveKey(ident)
    if derived then
      for _, lock in ipairs(LOCKS) do
        local candidate = {}
        for i = 1, #lock / 2 do
          local wrapped = tonumber(lock:sub(i * 2 - 1, i * 2), 16)
          local mask = tonumber(derived:sub(i * 2 - 1, i * 2), 16)
          candidate[i] = string.format('%02x', (wrapped - mask) % 256)
        end
        candidate = table.concat(candidate)
        if shaHex(candidate .. '#' .. BLOB) == TAG then return candidate end
      end
    end
  end
  return nil
end

local function decrypt()
  local key = unwrapKey()
  if not key then return nil end

  local out, blockIndex, keystream = {}, -1, nil
  for i = 1, #BLOB / 2 do
    local block = math.floor((i - 1) / 32)
    if block ~= blockIndex then
      blockIndex = block
      keystream = shaHex(key .. ':' .. block)
    end
    local offset = ((i - 1) % 32) * 2
    local keyByte = tonumber(keystream:sub(offset + 1, offset + 2), 16)
    local cipherByte = tonumber(BLOB:sub(i * 2 - 1, i * 2), 16)
    out[i] = string.char((cipherByte - keyByte) % 256)
  end
  return table.concat(out)
end

local function parseStations(plain)
  local list = {}
  for line in plain:gmatch('[^\n]+') do
    local id, frequency, name, urls = line:match('^([^|]*)|([^|]*)|([^|]*)|(.*)$')
    if id then
      local entry = { id = id, frequency = frequency, name = name, urls = {} }
      for url in urls:gmatch('[^\t]+') do
        entry.urls[#entry.urls + 1] = url
      end
      if #entry.urls > 0 then list[#list + 1] = entry end
    end
  end
  return list
end

local stations = {}
local licensed = false

do
  local plain = decrypt()
  if plain then
    stations = parseStations(plain)
    licensed = #stations > 0
  end
end

-- ------------------------------------------------------------------
--  Radio
-- ------------------------------------------------------------------

-- Seconds a stream gets to produce audio before we fall through to its backup.
local CONNECT_TIMEOUT = 9
-- Full passes through a station's URL list before giving up on it, so a dead
-- station can't sit there reconnecting forever in the background.
local MAX_PASSES = 3

local selected = 1
local urlIndex = 1
local passes = 0
local volume = 0.55
local muted = false
local powered = licensed
local player = nil
local status = licensed and 'STARTING' or 'LOCKED'
local statusDetail = licensed and 'Loading CSP native audio'
  or 'This server is not authorised to run this radio'
local statusTimer = 0
local sinceTune = 0
local toastTimer = 1.5
local toastShown = false

local function currentStation()
  return stations[selected]
end

local function applyVolume()
  if player then
    player:setVolume(volume)
    player:setMuted(muted or not powered)
  end
end

local function tune(index, urlIdx)
  if not licensed then return end
  selected = ((index - 1) % #stations) + 1
  local station = currentStation()
  urlIndex = urlIdx or 1

  if not ui.MediaPlayer.supported() then
    status = 'UNAVAILABLE'
    statusDetail = 'CSP native media playback is not supported on this PC'
    powered = false
    return
  end

  if not player then
    player = ui.MediaPlayer(nil, { rawOutput = false, use3D = false })
  end

  powered = true
  muted = false
  status = 'TUNING'
  statusDetail = 'Opening ' .. station.name
  player:setSource(station.urls[urlIndex])
  player:setAutoPlay(true)
  applyVolume()
  player:play()
  statusTimer = 0
  sinceTune = 0
end

local function stopRadio()
  powered = false
  status = 'STOPPED'
  statusDetail = 'Radio off'
  if player then
    player:pause()
    player:setMuted(true)
  end
end

local function togglePower()
  if powered then
    stopRadio()
  else
    passes = 0
    tune(selected, 1)
  end
end

local function radioUI()
  ui.textColored('RICHGUYLOS RADIO STATION', rgbm(0.08, 0.88, 1.00, 1))
  ui.textColored('SERVER RADIO // NO BRIDGE', rgbm(1.00, 0.12, 0.68, 1))
  ui.separator()

  if not licensed then
    ui.textColored('LOCKED', rgbm(1.00, 0.29, 0.29, 1))
    ui.textWrapped('This radio was created by RichGuyLos and is locked to his '
      .. 'servers. It will not run anywhere else.')
    ui.separator()
    -- Shown so an authorised server that fails to match can be identified and
    -- added to the build. It leaks nothing: this is the public address anyone
    -- already types in to connect.
    ui.textColored('This server reports:', rgbm(0.46, 0.58, 0.72, 1))
    for _, ident in ipairs(serverIdents()) do
      ui.text('  ' .. ident)
    end
    return false
  end

  local station = currentStation()
  ui.text(status .. '  //  ' .. station.frequency)
  ui.textWrapped(statusDetail)
  ui.separator()

  for i, item in ipairs(stations) do
    if ui.selectable(item.frequency .. '  //  ' .. item.name, selected == i) then
      passes = 0
      tune(i, 1)
    end
  end

  ui.separator()
  ui.text('AUDIO OUTPUT // CSP NATIVE')
  local nextVolume = ui.slider('##rglRadioVolume', volume * 100, 0, 100, '%.0f%%') / 100
  if math.abs(nextVolume - volume) > 0.001 then
    volume = nextVolume
    applyVolume()
  end

  if ui.button(powered and 'POWER OFF' or 'POWER ON', vec2(105, 32)) then
    togglePower()
  end
  ui.sameLine()
  if ui.button(muted and 'UNMUTE' or 'MUTE', vec2(90, 32)) then
    muted = not muted
    applyVolume()
  end
  ui.sameLine()
  if ui.button('RECONNECT', vec2(105, 32)) then
    passes = 0
    tune(selected, 1)
  end

  ui.textColored('Voice chat: CSP Mumble // positional PTT', rgbm(0.28, 1.00, 0.58, 1))
  return false
end

ui.registerOnlineExtra(
  ui.Icons.Radio,
  { title = 'RichGuyLos Radio Station', tooltip = 'Native server radio controls' },
  nil,
  radioUI,
  nil,
  ui.OnlineExtraFlags.Tool,
  ui.WindowFlags.None,
  vec2(390, 430)
)

if licensed then
  ui.MediaPlayer.supportedAsync(function (supported)
    if supported then
      tune(selected, 1)
    else
      status = 'UNAVAILABLE'
      statusDetail = 'CSP native media playback is not supported on this PC'
      powered = false
    end
  end)
end

function script.update(dt)
  if not licensed then return end

  statusTimer = statusTimer + dt
  sinceTune = sinceTune + dt
  toastTimer = toastTimer - dt

  if not toastShown and toastTimer <= 0 then
    toastShown = true
    ui.toast(ui.Icons.Radio, 'RichGuyLos Radio Station is playing. Open Chat > lightbulb for stations and volume.')
  end

  if not player or not powered then return end

  if player:playing() then
    -- Audio is flowing, so a stream that dies hours from now still gets a full
    -- set of retries rather than inheriting an old failure count.
    passes = 0
    if statusTimer >= 0.5 then
      statusTimer = 0
      status = muted and 'MUTED' or 'PLAYING'
      statusDetail = currentStation().name ..
        (urlIndex > 1 and ' // backup stream' or ' // live stream')
    end
    return
  end

  if sinceTune < CONNECT_TIMEOUT then
    if statusTimer >= 0.5 then
      statusTimer = 0
      status = player:hasAudio() and 'BUFFERING' or 'CONNECTING'
      statusDetail = 'Opening ' .. currentStation().name
    end
    return
  end

  -- Silent past the timeout: move to this station's next URL, and once the list
  -- is exhausted start it over until MAX_PASSES.
  local station = currentStation()
  if station.urls[urlIndex + 1] then
    tune(selected, urlIndex + 1)
  else
    passes = passes + 1
    if passes >= MAX_PASSES then
      status = 'UNAVAILABLE'
      statusDetail = station.name .. ' is not responding // pick another station'
      powered = false
      player:pause()
    else
      tune(selected, 1)
    end
  end
end
